version: '3'

services:
################################
#   Setup react app container
################################
  web:
    build: ./client
    expose:
      - 3000
    volumes:
      - ./client:/app

################################
#   Setup REDIS Server
################################
  redis:
    image: redis:3.2-alpine
    expose:
      - 6379
    volumes:
      - redis_data:/data
################################
#   Setup Socket Server container
################################
  server:
    build: ./server
    expose:
      - 3001
    depends_on: 
      - redis
    volumes:
      - ./server:/app
################################
#   Setup nginx load balancer
################################
  nginx:
    image: nginx:1.13 # this will use the latest version of 1.13.x
    ports:
      - '80:80' # expose 80 on host and sent to 80 in container
    depends_on: 
      - web
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
volumes:  
  redis_data:
