version: '3'

services:
  ################################
  #   Setup MongoDB
  ################################
  mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: chatapp
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data
  ################################
  #   Setup repository vertex
  ################################
  web:
    build: ./web
    depends_on:
      - chatroom-api
      - user-api
      - message-api
    expose:
      - 3000
  ################################
  #   Setup repository vertex
  ################################
  chatroom-api:
    build: ./chatroom-api
    depends_on:
      - mongodb
    expose:
      - 3000
  ################################
  #   Setup repository vertex
  ################################
  user-api:
    build: ./user-api
    depends_on:
      - mongodb
    expose:
      - 3000
  ################################
  #   Setup repository vertex
  ################################
  message-api:
    build: ./message-api
    depends_on:
      - mongodb
    expose:
      - 3000

################################
#   Setup nginx load balancer
################################
  nginx:
    build: ./nginx
    #image: nginx:1.13 # this will use the latest version of 1.13.x
    ports:
      - '80:80' # expose 80 on host and sent to 80 in container
    depends_on: 
      - web
    # volumes:
    #   - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    #   - ./client/img:/etc/nginx/html/img
volumes:
  mongodb_data:
