dist: trusty
language: java
jdk: openjdk8

install: true

script: ./.run.builds.sh

before_deploy: ./.run.jekyll.sh

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: _site
  on:
    branch: master
