= Single Page message sharing with React and Vert.x EventBus
:page-permalink: /
:page-github: vertx-howtos/single-page-react-vertx-howto

ifdef::env-github[]
image:https://travis-ci.org/vertx-howtos/single-page-react-vertx-howto.svg?branch=master["Build Status", link="https://travis-ci.org/vertx-howtos/single-page-react-vertx-howto"]
endif::env-github[]

This document will show you how to develop a Single Page Application (SPA) with React and Vert.x using EventBus

== What you will build

You will create a React frontend message syncronisation through EventBus with a Vert.x backend.
== How to execute
  #Build teh application using
  mvn clean install
  
  #Run the application using 
  mvn exec:java
  
== Summary

This document covered:

. The creation of a new React application with `create-react-app`
. running a frontend development server (for live-reload) that delegates API requests to the Vert.x backend
. bundling the frontend static files together with the Vert.x classes when going to production
. connecting frontend and backend using EventBus

== See also

- https://facebook.github.io/create-react-app/[Create React App]
- https://vertx.io/docs/vertx-web/java/[The Vert.x Web documentation]
